language: c

install:
  - sudo apt-get install cmake mono-devel mono-gmcs

script:
  - git submodule update --init --recursive
  - .nuget/Nuget.sh
  - cd libgit2sharp
  -  mkdir cmake-build
  -  cd cmake-build
  -   cmake -DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./libgit2-bin ../libgit2
  -   export LD_LIBRARY_PATH=$PWD/libgit2-bin/lib
  -   cmake --build . --target install
  -   cp -Rpv libgit2-bin/lib ../Lib/NativeBinaries/
  -  cd ..
  - cd ..
  - xbuild /p:TargetFrameworkProfile="" GitExtensionsMono.sln
